### ISSUE TITLE
Can't join the server!

### ISSUE THREAD

**Issue by gabber235** [Project-Cepi/KStom#26]
With the latest version of KStom and the latest version of Minestom (70b97951e4) I keep getting stuck in the `Joining world...` phase. 

How to replicate:
- Start a project
- Include Minestom 70b97951e4 and KStom (latest)
- Use the default server [Your first server](https://wiki.minestom.com/setup/your-first-server)
- Try to join with a client.

**Comment by LeoDog896** [comment]
Hey :wave: , even after reconnecting? Since KStom is a library and not an extension it shouldn't affect booting at all -- I recommend asking the people in the Minestom discord about this. If it helps, we use a default server jar called [Sabre](https://github.cepi.world/Sabre).

**Comment by gabber235** [comment]
I don't know why started working again. Thanks for the quick responds 😄
